name: Docker
"on":
  pull_request:
    branches:
      - main
  push:
    tags:
      - "*.*.*"

jobs:
  # https://github.com/edencehealth/workflows
  docker:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    permissions:
      contents: read
      packages: write
    with:
      container_name: msda_switchbox_db
      dockerhub_org: ""
      lfs: true
    secrets: inherit
